# ONDEWO T2S batch server configuration

inference_type: 'nemo'

caching:
    active: false
    memory_cache_max_size: 20
    sampling_rate: 22050
    load_cache: true
    save_cache: true
    cache_save_dir: "models/cache"


neural_factory:
    placement: 'GPU'
    batch_size: 1

tacotron2:
    nemo:
        config-path: "models/eloqai/de-AT/radiology001/sr001/0.0.1/tacotron2/tacotron2.yaml"
        path: "models/eloqai/de-AT/radiology001/sr001/0.0.1/tacotron2/"
        step: "7500"

waveglow:
    config-path: "models/eloqai/de-AT/radiology001/sr001/0.0.1/waveglow/waveglow.yaml"
    denoiser:
        active: true
        strength: 0.05
    nemo:
        path: "models/eloqai/de-AT/radiology001/sr001/0.0.1/waveglow/WaveGlowNM.pt"
        sigma: 0.6
    triton:
        triton_model: "waveglow"
        triton_url: "localhost:8001"