ARG PUSH_NAME_STREAM
FROM ${PUSH_NAME_STREAM} AS test

COPY ./docker/test_requirements.txt .

RUN pip install nvidia-pyindex
RUN pip install -r test_requirements.txt --ignore-installed


WORKDIR /opt/ondewo-t2s
COPY ./normalization ./normalization
COPY ./inference ./inference
COPY ./rest_server ./rest_server
COPY ./utils ./utils
COPY ./tests ./tests
COPY ./config ./config

ENV PYTHONPATH /opt/ondewo-t2s
ENTRYPOINT [ "python", "-m", "pytest", "-vv", "--capture=no", "--junit-xml=log/${TESTFILE}", "--ignore=tests/e2e", "--ignore=tests/integration", "--ignore=tests/tests_grpc_unit"]