FROM dockerregistry.ondewo.com:5000/cuda:11.0-base-ubuntu18.04 AS uncythonized

RUN apt-get update && apt-get -y upgrade && \
	apt-get install -y git

# Upgrade installed packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y libsndfile1-dev

# Install Python 3.7
RUN apt-get install -y curl python3.7 python3.7-dev python3.7-distutils && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1 && \
    update-alternatives --set python /usr/bin/python3.7 && \
    curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py

# Install PyTorch
RUN pip install torch==1.6.0

# Install NeMo
RUN pip install nemo_toolkit[all]==0.11

COPY ./glow-tts ./glow-tts
RUN cd glow-tts/monotonic_align; python setup.py build_ext --inplace; cd ../..
RUN pip install -e glow-tts

COPY docker/test_requirements.txt .
RUN pip install -r test_requirements.txt --ignore-installed
WORKDIR /opt

WORKDIR /opt/ondewo-t2s
COPY ./normalization ./normalization
COPY ./inference ./inference
COPY ./batch_server ./batch_server
COPY ./utils ./utils
COPY ./tests ./tests
COPY ./config ./config

ENV PYTHONPATH /opt/ondewo-t2s
CMD python -m pytest -vv --capture=no --junit-xml=log/"$TESTFILE" --ignore="tests/e2e"