FROM dockerregistry.ondewo.com:5000/nemo:master AS uncythonized

COPY ./docker/batch_server_requirements.txt .
RUN pip install -r batch_server_requirements.txt --ignore-installed

WORKDIR /opt/ondewo-t2s-stella
COPY ./utils ./utils
RUN cd utils/triton_client_lib && pip install --user --upgrade triton*.whl

COPY ./inference ./inference
COPY ./normalization ./normalization
COPY ./batch_server ./batch_server


ENV PYTHONPATH /opt/ondewo-t2s-stella
ENV FLASK_APP batch_server
CMD flask run --host=0.0.0.0 --port=40015


# ========Cythonization Image=======
FROM dockerregistry.ondewo.com:5000/ondewo-cythonize-tools-3.7 AS cython_builder

COPY --from=uncythonized /opt/ondewo-t2s-stella/batch_server /tmp/transfer/to_cythonize/batch_server
COPY --from=uncythonized /opt/ondewo-t2s-stella/inference /tmp/transfer/to_cythonize/inference
COPY --from=uncythonized /opt/ondewo-t2s-stella/normalization /tmp/transfer/to_cythonize/normalization
COPY --from=uncythonized /opt/ondewo-t2s-stella/utils/logger.py /tmp/transfer/to_cythonize/utils/logger.py
COPY --from=uncythonized /opt/ondewo-t2s-stella/utils/version.py /tmp/transfer/to_cythonize/utils/version.py
COPY --from=uncythonized /opt/ondewo-t2s-stella/utils/constants.py /tmp/transfer/to_cythonize/utils/constants.py

RUN ./cythonize.py \
		--modules_to_cythonize ./to_cythonize \
		--files_to_skip ./to_cythonize/batch_server/__init__.py \
        --directories_to_skip "./to_cythonize/inference/nemo_modules" \
        --delete_pycache True \
		--py_files_mode delete


# ========Cythonized================
FROM uncythonized AS cythonized

RUN rm -r ./*
COPY --from=cython_builder /tmp/transfer/to_cythonize/ .
