name: "mb_melgan",
platform: "tensorflow_savedmodel",
backend: "tensorflow",
version_policy: {
    latest: {
        num_versions: 1
    }
},
max_batch_size: 1,
input: [
    {
        name: "input_1",
        data_type: TYPE_FP32,
        dims: [
            -1,
            80
        ]
    }
],
output: [
    {
        name: "output_1",
        data_type: TYPE_FP32,
        dims: [
            -1,
            1
        ]
    }
],
batch_input: [],
batch_output: [],
optimization: {
    priority: PRIORITY_DEFAULT,
    input_pinned_memory: {
        enable: true
    },
    output_pinned_memory: {
        enable: true
    }
},
instance_group: [
    {
        name: "mb_melgan",
        kind: KIND_GPU,
        count: 1,
        gpus: [
            0
        ],
        profile: []
    }
],
default_model_filename: "model.savedmodel",
cc_model_filenames: {},
metric_tags: {},
parameters: {},
model_warmup: [],
dynamic_batching: {}
