# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_config_server.ondewo.audio import text_to_speech_pb2 as ondewo_dot_audio_dot_text__to__speech__pb2


class Text2SpeechConfigurationStub(object):
    """option cc_enable_arenas = true;
    option csharp_namespace = "Google.Cloud.Dialogflow.V2";
    option go_package = "google.golang.org/genproto/googleapis/cloud/dialogflow/v2;dialogflow";
    option java_multiple_files = true;
    option java_outer_classname = "VoipProto";
    option java_package = "com.google.cloud.dialogflow.v2";
    option objc_class_prefix = "DF";

    configuration of text-to-speech
    endpoints of text-to-speech service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSupportedLanguages = channel.unary_unary(
                '/ondewo.nlu.Text2SpeechConfiguration/ListSupportedLanguages',
                request_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesRequest.SerializeToString,
                response_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesResponse.FromString,
                )
        self.ListModelSetupsForLanguage = channel.unary_unary(
                '/ondewo.nlu.Text2SpeechConfiguration/ListModelSetupsForLanguage',
                request_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListModelSetupsForLangRequest.SerializeToString,
                response_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.FromString,
                )
        self.ListAllModelSetups = channel.unary_unary(
                '/ondewo.nlu.Text2SpeechConfiguration/ListAllModelSetups',
                request_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListAllModelSetupsRequest.SerializeToString,
                response_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.FromString,
                )
        self.GetActiveModelConfig = channel.unary_unary(
                '/ondewo.nlu.Text2SpeechConfiguration/GetActiveModelConfig',
                request_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.GetActiveModelConfigRequest.SerializeToString,
                response_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupResponse.FromString,
                )
        self.SetModelConfig = channel.unary_unary(
                '/ondewo.nlu.Text2SpeechConfiguration/SetModelConfig',
                request_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigRequest.SerializeToString,
                response_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigResponse.FromString,
                )


class Text2SpeechConfigurationServicer(object):
    """option cc_enable_arenas = true;
    option csharp_namespace = "Google.Cloud.Dialogflow.V2";
    option go_package = "google.golang.org/genproto/googleapis/cloud/dialogflow/v2;dialogflow";
    option java_multiple_files = true;
    option java_outer_classname = "VoipProto";
    option java_package = "com.google.cloud.dialogflow.v2";
    option objc_class_prefix = "DF";

    configuration of text-to-speech
    endpoints of text-to-speech service
    """

    def ListSupportedLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelSetupsForLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllModelSetups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModelConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Text2SpeechConfigurationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSupportedLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedLanguages,
                    request_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesRequest.FromString,
                    response_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesResponse.SerializeToString,
            ),
            'ListModelSetupsForLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelSetupsForLanguage,
                    request_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListModelSetupsForLangRequest.FromString,
                    response_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.SerializeToString,
            ),
            'ListAllModelSetups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllModelSetups,
                    request_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.ListAllModelSetupsRequest.FromString,
                    response_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.SerializeToString,
            ),
            'GetActiveModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveModelConfig,
                    request_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.GetActiveModelConfigRequest.FromString,
                    response_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupResponse.SerializeToString,
            ),
            'SetModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModelConfig,
                    request_deserializer=ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigRequest.FromString,
                    response_serializer=ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ondewo.nlu.Text2SpeechConfiguration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Text2SpeechConfiguration(object):
    """option cc_enable_arenas = true;
    option csharp_namespace = "Google.Cloud.Dialogflow.V2";
    option go_package = "google.golang.org/genproto/googleapis/cloud/dialogflow/v2;dialogflow";
    option java_multiple_files = true;
    option java_outer_classname = "VoipProto";
    option java_package = "com.google.cloud.dialogflow.v2";
    option objc_class_prefix = "DF";

    configuration of text-to-speech
    endpoints of text-to-speech service
    """

    @staticmethod
    def ListSupportedLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.Text2SpeechConfiguration/ListSupportedLanguages',
            ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesRequest.SerializeToString,
            ondewo_dot_audio_dot_text__to__speech__pb2.ListLanguagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListModelSetupsForLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.Text2SpeechConfiguration/ListModelSetupsForLanguage',
            ondewo_dot_audio_dot_text__to__speech__pb2.ListModelSetupsForLangRequest.SerializeToString,
            ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAllModelSetups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.Text2SpeechConfiguration/ListAllModelSetups',
            ondewo_dot_audio_dot_text__to__speech__pb2.ListAllModelSetupsRequest.SerializeToString,
            ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActiveModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.Text2SpeechConfiguration/GetActiveModelConfig',
            ondewo_dot_audio_dot_text__to__speech__pb2.GetActiveModelConfigRequest.SerializeToString,
            ondewo_dot_audio_dot_text__to__speech__pb2.ModelSetupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ondewo.nlu.Text2SpeechConfiguration/SetModelConfig',
            ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigRequest.SerializeToString,
            ondewo_dot_audio_dot_text__to__speech__pb2.SetModelConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
