# Stella S2T server configuration


inference_type: 'nemo'

neural_factory:
    placement: 'GPU'
    backend: 'pytorch'

tacotron2:
    nemo:
        config-path: "models/tacotron2/de/tacotron2.yaml"
        path: "models/tacotron2/de/checkpoints_kerstin_eloqai/"
        step: "3000"

waveglow:
    inference_type: 'nemo'
    config-path: "models/waveglow/waveglow.yaml"
    nemo:
        path: "models/waveglow/checkpoints_waveglow_kerstin/WaveGlowNM.pt"
        sigma: 0.6
    triton:
        triton_model: "waveglow"
