# Stella S2T server configuration

inference_type: 'Nemo'

neural_factory_nemo:
    placement: 'GPU'
    backend: 'pytorch'

tacotron2:
    config-path: "models/tacotron2/de/tacotron2.yaml"
    path: "models/tacotron2/de/kerstin_PUN/"
    step: 1000

waveglow:
    config-path: "models/waveglow/waveglow.yaml"
    triton-url: "localhost:8001"
    triton-model: "waveglow"

