# Stella S2T server configuration

tacotron2:
    config-path: "models/tacotron2/de/tacotron2.yaml"
    path: "models/tacotron2/de/kerstin_PUN/"
    step: "1000"

waveglow:
    config-path: "models/waveglow/waveglow.yaml"
    path: "models/waveglow/kerstin/WaveGlowNM-STEP-500.pt"
    sigma: 0.6
