# Stella S2T server configuration


inference_type: 'nemo'

neural_factory:
    placement: 'GPU'
    backend: 'pytorch'
    batch_size: 1

tacotron2:
    nemo:
        config-path: "models/tacotron2/de/tacotron2.yaml"
        path: "models/tacotron2/de/kerstin_PUN/"
        step: "1000"

waveglow:
    inference_type: 'nemo'
    config-path: "models/waveglow/waveglow.yaml"
    nemo:
        path: "models/waveglow/kerstin/WaveGlowNM-STEP-500.pt"
        sigma: 0.6
    triton:
        triton_model: "waveglow"
