id: glow_tts&hifi_gan-e976dd6c-2f41-484b-aec2-3e6868d37280
description:
  language: en
  speaker_sex: female
  pipeline_owner: ondewo
  comments: trained on public domain dataset Lj_speech
  speaker_name: Linda
  domain: general
active: true
inference:
  type: composite
  composite_inference:
    text2mel:
      type: glow_tts
      glow_tts:
        batch_size: 5
        use_gpu: false
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        path: models/glow-tts/en/pretrained.pth
        param_config_path: models/glow-tts/en/config.json
        cleaners: []
      glow_tts_triton:
        batch_size: 8
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        cleaners: []
        max_text_length: 100
        param_config_path: models/glow-tts/en/config.json
        triton_url: localhost:50511
        triton_model_name: glow_tts
    mel2audio:
      type: hifi_gan
      mb_melgan_triton:
        config_path: models/mb_melgan/en/config.yml
        stats_path: models/mb_melgan/en/stats.npy
        triton_model_name: mb_melgan
        triton_url: localhost:50511
      hifi_gan:
        use_gpu: false
        batch_size: 20
        config_path: models/HiFiGan/config.json
        model_path: models/HiFiGan/g_02500000
      hifi_gan_triton:
        config_path: models/HiFiGan/universal/config.json
        triton_model_name: hifi_tts
        triton_url: localhost:50511
  caching:
    active: false
    memory_cache_max_size: 20
    sampling_rate: 22050
    load_cache: true
    save_cache: true
    cache_save_dir: models/cache
normalization:
  language: en
  pipeline: []
  custom_phonemizer_id: ''
postprocessing:
  silence_secs: 0.25
  pipeline: []
  logmmse:
    initial_noise: 100
    window_size: 0
    noise_threshold: 0.15000000596046448
  wiener:
    frame_len: 1024
    lpc_order: 50
    iterations: 10
    alpha: 0.5
    thresh: 0.10000000149011612
  apodization:
    apodization_secs: 0.25
