# ONDEWO T2S batch server configuration


inference:
    type: "composite"

    composite_inference:
        text2mel:
            type: "tacotron2"

            tacotron2:
                param_config_path: "models/tacotron2/de/tacotron2.yaml"
                path: "models/tacotron2/de/kerstin_PUN/"
                step: "1000"

        mel2audio:
            type: "waveglow_triton"

            waveglow:
                param_config_path: "models/waveglow/waveglow.yaml"
                path: "models/waveglow/pretrained/WaveGlowNM.pt"
                sigma: 0.6
                denoiser:
                    active: true
                    strength: 0.05

            waveglow_triton:
                param_config_path: "models/waveglow/waveglow.yaml"
                sigma: 0.6
                max_spect_size: 200
                triton_model_name: "waveglow"
                triton_url: "localhost:8001"

    caching:
        active: false
        memory_cache_max_size: 20
        sampling_rate: 22050
        load_cache: true
        save_cache: true
        cache_save_dir: "models/cache"