active: true
description: {comments: trained on public domain dataset Lj_speech, language: en,
  pipeline_owner: ondewo, speaker_sex: female}
id: glow_tts&hifi_gan-0118e07a-8447-4c87-9f6b-4802a7dd7a07
inference:
  caching: {active: false, cache_save_dir: models/cache, load_cache: true, memory_cache_max_size: 20,
    sampling_rate: 22050, save_cache: true}
  composite_inference:
    mel2audio:
      hifi_gan: {batch_size: 20, config_path: models/HiFiGan/universal/config.json,
        model_path: models/HiFiGan/universal/g_02500000, use_gpu: true}
      mb_melgan_triton: {config_path: models/mb_melgan/en/config.yml, stats_path: models/mb_melgan/en/stats.npy,
        triton_model_name: mb_melgan, triton_url: "localhost:8001"}
      type: hifi_gan
    text2mel:
      glow_tts:
        batch_size: 5
        cleaners: []
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        param_config_path: models/glow-tts/en/config.json
        path: models/glow-tts/en/pretrained.pth
        use_gpu: true
      glow_tts_triton:
        batch_size: 8
        cleaners: []
        length_scale: 1.0
        max_text_length: 100
        noise_scale: 0.6669999957084656
        param_config_path: models/glow-tts/en/config.json
        triton_model_name: glow_tts
        triton_url: localhost:8001
      type: glow_tts
  type: composite
normalization:
  language: en
  pipeline: [normalise_simple]
postprocessing:
  apodization: {apodization_secs: 0.25}
  logmmse: {initial_noise: 100, noise_threshold: 0.15000000596046448, window_size: 0}
  pipeline: []
  silence_secs: 0.25
  wiener: {alpha: 0.5, frame_len: 1024, iterations: 10, lpc_order: 50, thresh: 0.10000000149011612}
