id: glow_tts&hifi_gan-0118e07a-8447-4c87-9f6b-4802a7dd7a07
description:
  language: en
  speaker_sex: female
  pipeline_owner: ondewo
  comments: trained on public domain dataset Lj_speech
  speaker_name: Linda
  domain: general
active: true
inference:
  type: composite
  composite_inference:
    text2mel:
      type: glow_tts
      glow_tts:
        batch_size: 5
        use_gpu: true
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        path: models/glow-tts/en/pretrained.pth
        param_config_path: models/glow-tts/en/config.json
        cleaners: []
      glow_tts_triton:
        batch_size: 8
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        cleaners: []
        max_text_length: 100
        param_config_path: models/glow-tts/en/config.json
        triton_url: localhost:50511
        triton_model_name: glow_tts
    mel2audio:
      type: hifi_gan
      mb_melgan_triton:
        config_path: models/mb_melgan/en/config.yml
        stats_path: models/mb_melgan/en/stats.npy
        triton_model_name: mb_melgan
        triton_url: localhost:50511
      hifi_gan:
        use_gpu: true
        batch_size: 20
        config_path: models/HiFiGan/universal/config.json
        model_path: models/HiFiGan/universal/g_02500000
      hifi_gan_triton:
        config_path: models/HiFiGan/universal/config.json
        triton_model_name: hifi_tts
        triton_url: localhost:50511
  caching:
    active: false
    memory_cache_max_size: 20
    sampling_rate: 22050
    load_cache: true
    save_cache: true
    cache_save_dir: models/cache
normalization:
  language: en
  pipeline: []
  custom_phonemizer_id:
  arpabet_mappping:
  - 'a: {AH1 AH1 AH1 AH1 AH1}'
  - 'b: {V AY X EH S}, {B EH EH EH EH1}'
  - 'c: {TZ EH EH EH EH EH1}'
  - 'd: {V AY X EH S}, {D EH EH EH EH1 EH1}'
  - 'e: {EH EH EH EH EH1}'
  - 'f: {EH EH F F F F}'
  - 'g: {G EH EH EH EH1}'
  - 'h: {HH AH AH AH1 AH1 AH1 AH1}'
  - 'i: {IH IH IH IH}'
  - 'j: {Y O1 T T T T}'
  - 'k: {K AH AH AH AH1 AH1 AH1}'
  - 'l: {EH EH L L L L L L L}'
  - 'm: {EH EH M M M}'
  - 'n: {EH EH N N N N N N N}'
  - 'o: {O1 O1 O1 O1 O1}'
  - 'p: {HH A R T EH S}, {P EH1 EH1}'
  - 'q: {K UH UH UH UH}'
  - 'r: {EH EH1 R R R R}'
  - 's: {EH S S S}'
  - 't: {HH A R T EH S}, {T EH1 EH1 EH1}'
  - 'u: {UH UH UH UH UH}'
  - 'v: {F F AH AW UH UH UH}'
  - 'w: {V EH EH EH1}'
  - 'x: {IH K S S S}'
  - 'y: {YO YO P S S IY1 L O1 N}'
  - 'z: {T Z EH T T}'
  - 'ä: {UH M L AW T}, {EH EH EH EH EH EH EH EH}'
  - 'ö: {UH M L AW T}, {OE OE OE OE1 OE1 OE1 OE1}'
  - 'ü: {UH M L AW T}, {YO YO1 YO1}'
  - 'ß: {SH A R F EH S}. {EH S S}'
  - '/: {SH RR EH K SH T R IH X}'
  - '.: {P UH N K K T}'
  - '!: {AW S RR UW F EH1 TZ AY X EH N}'
  - '#: {HH A SH}, {T AH1 AH1 G}'
  - '$: {D AO L L AH1 R}, {TZ AY X EH N}'
  - '*: {SH T EH R N X EH N}'
  - '&: {UH N T T}, {TZ AY X EH N}'
  - '(: {L IH NG K EH1}, {K L A M E RR RR}'
  - '): {RR EH X T EH}, {K L A M E RR RR}'
  - '-: {B IH N D EH SH T R IH X}'
  - '_: {UH N T AR SH T R IH X}'
  - '+: {P L UH S}, {TZ AY X EH N}'
  - '=: {IH S T} {G L AY X} {TZ AY X EH N}'
  - '?: {F RR AH1 G EH1}, {TZ AY X EH N}'
postprocessing:
  silence_secs: 0.25
  pipeline: []
  logmmse:
    initial_noise: 100
    window_size: 0
    noise_threshold: 0.15000000596046448
  wiener:
    frame_len: 1024
    lpc_order: 50
    iterations: 10
    alpha: 0.5
    thresh: 0.10000000149011612
  apodization:
    apodization_secs: 0.25
