active: true
description: {comments: trained on public domain dataset, language: de, pipeline_owner: ondewo,
  speaker_sex: male}
id: glow_tts&hifi_gan-e976dd6c-2f41-484b-aec2-3e6868d37280
inference:
  caching: {active: false, cache_save_dir: models/cache, load_cache: true, memory_cache_max_size: 20,
    sampling_rate: 22050, save_cache: true}
  composite_inference:
    mel2audio:
      hifi_gan: {batch_size: 20, config_path: models/HiFiGan/universal/config.json,
        model_path: models/HiFiGan/universal/g_02500000, use_gpu: true}
      mb_melgan_triton: {config_path: models/mb_melgan/en/config.yml, stats_path: models/mb_melgan/en/stats.npy,
        triton_model_name: mb_melgan, triton_url: "localhost:8001"}
      type: hifi_gan
    text2mel:
      glow_tts:
        batch_size: 5
        cleaners: []
        length_scale: 1.0
        noise_scale: 0.6669999957084656
        param_config_path: models/glow-tts/de/config_blank.json
        path: models/glow-tts/de/thorsten_blank.pth
        use_gpu: true
      glow_tts_triton:
        batch_size: 8
        cleaners: []
        length_scale: 1.0
        max_text_length: 100
        noise_scale: 0.6669999957084656
        param_config_path: models/glow-tts/de/config.json
        triton_model_name: glow_tts
        triton_url: localhost:8001
      type: glow_tts
  type: composite
normalization:
  language: de
  pipeline: [fix_plus, normalize_urls, normalize_dates, normalize_year, normalize_time,
    normalize_numbers, fix_punctuation, remove_unaudible_texts, lower_case]
postprocessing:
  apodization: {apodization_secs: 0.25}
  logmmse: {initial_noise: 100, noise_threshold: 0.15000000596046448, window_size: 0}
  pipeline: []
  silence_secs: 0.25
  wiener: {alpha: 0.5, frame_len: 1024, iterations: 10, lpc_order: 50, thresh: 0.10000000149011612}
