version: '3'
services:

  voip_server:
    container_name: t2s_grpc_server
    build:
      context: .
      dockerfile: Dockerfile
    image: t2s_grpc_server
    ports:
      - 7777:7777
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock

