# This is a basic workflow to help you get started with Actions

name: Generate API Documentation

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate-docs"
  generate-doc-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: true

      # - uses: actions/setup-go@v2.1.3

      # - name: Single command step
      #   run: sudo apt install -y protobuf-compiler

      # - name: Multi-line command step
      #   run: |
      #     go get -u github.com/pseudomuto/protoc-gen-docs/cmd/protoc-gen-docs
      #     export PATH=$(go env GOPATH)/bin:$PATH
      #     mkdir -p docs
      #     protoc -I. -Igoogleapis --doc_opt=markdown,nlu.md --doc_out=docs $(find ondewo -name '*.proto' | sort)

      - name: Generate documentation from ONDEWO proto files 🔧
        uses: ondewo/ondewo-protoc-gen-doc-action@master


      - name: Deploy 🚀
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder, of which contents the action should deploy.
          target-folder: docs # The target folder, to which the action should deploy the folder contents
